server:
  port: 60011

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true
#hystrix?????
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon?????
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

spring:
  application:
    name: spring-cloud-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: spring-cloud-consumer
          uri: lb://spring-cloud-consumer
          predicates:
            - Path=/api/consumer/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
