server:
  port: 10081

spring:
  application:
    name: spring-cloud-consumer # Spring ???

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos ?????
        service: ${spring.application.name} # ??? Nacos ??????? ${spring.application.name}?
